### ISSUE TITLE
Please tell me which model are best or What difference between these models

### ISSUE THREAD

**Issue by seetimee** [Monkfishare/Topaz#1]

**Comment by Monkfishare** [comment]
- https://docs.topazlabs.com/photo-ai/features
- Typically, these model files are used within Topaz Labs software for tasks such as denoising, upscaling, sharpening, or other image enhancement tasks and features. It's difficult to determine the exact function or purpose of specific models referring to their filenames. If you need more information about this specific model file or how to use it, you may want to consult the documentation or support resources provided by [Topaz Labs](https://community.topazlabs.com/).

**Comment by seetimee** [comment]
Thanks
