### ISSUE TITLE
求更新3.0版的

### ISSUE THREAD

**Issue by leslie-DL** [Monkfishare/Topaz#2]
感谢分享下载列表，不知道3.0的是否有大变化

**Comment by novopu** [comment]
Version: [3.0.3](https://downloads.topazlabs.com/deploy/TopazPhotoAI/3.0.3/TopazPhotoAI-3.0.3.msi) (Windows), one model below needed to be updated.
一个模型需更新，https://models.topazlabs.com/v1/WhiteBalanceData-v2.bin
